name: Infra Ecobytes

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      action:
        description: "Create or destroy infrastructure"
        required: true
        type: choice
        options:
          - create
          - destroy
          - build_backend
          - deploy_backend
          # - build_frontend
          # - deploy_frontend
      environment:
        description: "Chose infrastructure environment to be created"
        required: true
        type: choice
        options:
          - dev
          # - prod    

permissions:
  id-token: write
  contents: read

jobs:
  install-infra:
    if: github.event.inputs.action == 'create' || github.event_name == 'push' || github.event_name == 'pull_request' || github.event.inputs.action == 'deploy_frontend'
    uses: ./.github/workflows/infra-create.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      trigger_event: ${{ github.event.inputs.action }}

  uninstall-infra:
    if: github.event.inputs.action == 'destroy'
    uses: ./.github/workflows/infra-destroy.yaml

  build-backend:
    if: github.event.inputs.action == 'build_backend' || github.event.inputs.action == 'deploy_backend'
    uses: epm-pebt/back/.github/workflows/gradle.yml@CI-CD-restructured
    # permissions:
    #   id-token: write
    #   contents: write
    with:
      environment: ${{ github.event.inputs.environment }}
      token: ${{ secrets.GITHUB_TOKEN }}

# TODO: try to make this step fitting for back and front deliver

  deliver-backend:
    if: github.event.inputs.action == 'deploy_backend'
    needs: build-backend
    uses: epm-pebt/infra/.github/workflows/infra-create.yaml@CI-CD-restructured
    with:
      environment: ${{ github.event.inputs.environment }}
      trigger_event: ${{ github.event.inputs.action }}
  
  deploy-backend:
    if: github.event.inputs.action == 'deploy_backend'
    needs: deliver-backend
    uses: epm-pebt/back/.github/workflows/docker-deploy.yaml@CI-CD-restructured
    permissions:
      id-token: write
      contents: read

# TODO: finish step beyond

  # build-frontend:
  #   if: github.event.inputs.action == 'build_frontend' || github.event.inputs.action == 'deploy_frontend'
  #   needs: install-infra
  #   uses: marinaimeninnik/eco-bites-front/.github/workflows/build-react.yaml@CI-CD_pipeline
  #   permissions:
  #     id-token: write
  #     contents: read